# PDNUART: 0
# TMC_TX: 1
# LED BlUE: 2
# LIMIT 2: 3
# LED RED: 4
# BUZZER: 5
# INDEX: 6
# TMC_EN: 8
# Acceleromter Inerrupt: 12
# LIMIT 1: 15
# SDA: 19
# SCL: 20
# Button Calibration: 21
# Button Move: 29

external_components:
  - source: github://slimcdk/esphome-custom-components
    components: [tmc2209_hub, tmc2209, stepper]

## 1.91666666667 revolutions to move 1mm
## 121 mm travel distance

# 1.9167 x 121 = 231.9207 revolutions to move full distance

substitutions:
  stepper_direction: "ccw" # change to "cw" or "ccw" to change direction

  steps_per_revolution: "1600"
  max_distance_revs: "float(231.9207)"

  max_distance_steps: "${max_distance_revs}*${steps_per_revolution}" # converts cm to steps. Use this in remaining code

api:

ota:
  - platform: esphome

logger:

esp32:
  board: esp32-c6-devkitm-1
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esphome:
  name: ropener-office
  on_boot:
    - tmc2209.configure:
        direction: ${stepper_direction}
        microsteps: 8
        interpolation: true
    - tmc2209.stallguard:
        threshold: 50
    - tmc2209.currents:
        standstill_mode: freewheeling
        #irun: 20 # 0-31. 31 = 2A current
        run_current: 400
        ihold: 0
        tpowerdown: 0
        iholddelay: 0

uart:
  tx_pin: 1
  rx_pin: 0
  baud_rate: 500000

stepper:
  - platform: tmc2209
    id: driver
    max_speed: 1000 steps/s # Faster speed is louder
    acceleration: 1000 steps/s^2
    deceleration: 1000 steps/s^2
    config_dump_include_registers: true
    rsense: 220 mOhm
    vsense: False
    enn_pin: 8
    index_pin: 0
    diag_pin: 1
    on_stall:
      - stepper.stop: driver
      - stepper.report_position:
          id: driver
          position: !lambda return ${max_distance_steps};
      - logger.log: "Homed cover"

binary_sensor:
 - platform: gpio
   name: Button 1
   id: btn1
   pin:
     number: 29
     mode: INPUT
     inverted: true
   filters:
     - delayed_on: 10ms
   on_release:
    then:
    - cover.close: ropener_cover
   on_double_click:
     then:
     - cover.open: ropener_cover

 - platform: gpio
   name: Limit Switch 1
   id: limit_switch_1
   pin:
     number: 15
     mode: INPUT
     inverted: true
    # ...
   on_press:
     then:
     - cover.stop: ropener_cover

 - platform: gpio
   name: Limit Switch 2
   id: limit_switch_2
   pin:
     number: 3
     mode: INPUT
     inverted: true
    # ...
   on_press:
     then:
     - cover.stop: ropener_cover



cover:
  - platform: template
    id: ropener_cover
    name: Ropener
    has_position: true
    assumed_state: false
    lambda: "return 1.0 - (id(driver)->current_position / ${max_distance_steps});"
    stop_action:
      - stepper.stop: driver
    open_action:
      - stepper.set_target:
          id: driver
          target: 0
    open_endstop: limit_switch_1
    close_action:
      - stepper.set_target:
          id: driver
          target: !lambda return ${max_distance_steps};
    close_endstop: limit_switch_2
    position_action:
      - stepper.set_target:
          id: driver
          target: !lambda return (1.0 - pos) * ${max_distance_steps};
          
button:
  - platform: template
    name: Set Close Position
    on_press:
      - stepper.report_position:
          id: driver
          position: !lambda return ${max_distance_steps};