external_components:
  - source: github://slimcdk/esphome-custom-components
    components: [tmc2209_hub, tmc2209, stepper]

substitutions:
  steps_per_revolution: "1600"
  max_distance_revs: "float(231.9207)"
  max_distance_steps: 341387 # converts cm to steps. Use this in remaining code

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome

logger:
  level: VERBOSE
  hardware_uart: UART0

esp32:
  variant: esp32c6
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  on_connect:
    then:
      - logger.log: "Connected to WiFi! Running post-connect actions."
      - if:      # NEED TO CHECK IF EITHER LIMIT SWITCH IS PRESSED AND SET POSITION BASED ON THAT
          condition:
            binary_sensor.is_on: limit_switch_1  # Check if switch is pressed
          then:
            - logger.log: "SETTING LIMIT 1"
            - cover.template.publish:
                id: glasscalibur_cover
                position: 1.0
            - stepper.report_position:
                id: driver
                position: ${max_distance_steps}
            - stepper.set_target:
                id: driver
                target: ${max_distance_steps}

      - if:
          condition:
            binary_sensor.is_on: limit_switch_2  # Check if switch is pressed
          then:
            - logger.log: "SETTING LIMIT 2"
            - cover.template.publish:
                id: glasscalibur_cover
                position: 0
            - stepper.report_position:
                id: driver
                position: 0
            - stepper.set_target:
                id: driver
                target: 0

esphome:
  name: "glasscalibur-1"
  on_boot:
    # - priority: -100
    #   then:
      - logger.log: "CHECKING LIMIT SWITCHES"
      - if:      # NEED TO CHECK IF EITHER LIMIT SWITCH IS PRESSED AND SET POSITION BASED ON THAT
          condition:
            binary_sensor.is_on: limit_switch_1  # Check if switch is pressed
          then:
            - logger.log: "SETTING LIMIT 1"
            - stepper.report_position:
                id: driver
                position: ${max_distance_steps}
            - stepper.set_target:
                id: driver
                target: ${max_distance_steps}
      - if:
          condition:
            binary_sensor.is_on: limit_switch_2  # Check if switch is pressed
          then:
            - logger.log: "SETTING LIMIT 2"
            - stepper.report_position:
                id: driver
                position: 0
            - stepper.set_target:
                id: driver
                target: 0

      - tmc2209.configure:
          direction: ccw
          microsteps: 8
          interpolation: true
      - tmc2209.stallguard:
          threshold: 50
      - tmc2209.currents:
          standstill_mode: freewheeling
          irun: 25 # 26 = 0.6A current. DO NOT EXCEED. MOTOR GETS STUPID HOT.
          ihold: 0
          tpowerdown: 0
          iholddelay: 0

output:
  - platform: ledc
    pin: GPIO5
    id: buzzer

uart:
  tx_pin: 1
  rx_pin: 0
  baud_rate: 500000

stepper:
  - platform: tmc2209
    id: driver
    # max_speed: 1200 steps/s # Faster speed is louder #2000 good. #1500 great
    max_speed: 1200 steps/s # Faster speed is louder #2000 good. #1500 great
    acceleration: 100 steps/s^2
    deceleration: 100000 steps/s^2 # Stop very fast in case limit swith reached
    config_dump_include_registers: true
    rsense: 220 mOhm
    vsense: False
    enn_pin: 8
    index_pin: 6
    diag_pin: 14
    #on_stall:
      #- stepper.stop: driver

binary_sensor:
  - platform: gpio
    name: Button 1
    id: btn1
    pin:
      number: GPIO23
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: 10ms
    on_multi_click:

      # --- Single Click ---
      - timing:
          - ON for at most 1.0s
          - OFF for at least 0.5s
        then:
          - cover.close: glasscalibur_cover
          # - if:
          #     condition: ## If moving, then stop
          #       lambda: return (id(glasscalibur_cover).current_operation != COVER_OPERATION_IDLE); # Should evaluate to TRUE if moving
          #     then:
          #       - cover.stop: glasscalibur_cover
          #     else: ## If not moving, then close
          #       - cover.close: glasscalibur_cover

          # - output.turn_on: buzzer
          # - output.ledc.set_frequency:
          #     id: buzzer
          #     frequency: "2700Hz"
          # - output.set_level:
          #     id: buzzer
          #     level: "50%"
          # - delay: 1s
          # - output.turn_off: buzzer

      # --- Double Click ---          
      - timing:
          - ON for at most 1.0s
          - OFF for at most 0.3s
          - ON for at most 1.0s
          - OFF for at least 0.5s
        then:
          - cover.open: glasscalibur_cover

          # - output.turn_on: buzzer
          # - output.ledc.set_frequency:
          #     id: buzzer
          #     frequency: "2700Hz"
          # - output.set_level:
          #     id: buzzer
          #     level: "50%"
          # - delay: 1s
          # - output.turn_off: buzzer

  - platform: gpio
    name: Open Limit Switch
    id: limit_switch_1
    pin:
      number: GPIO15
      mode: INPUT
      inverted: true
    # Interrupts are not reliable, they constatnly miss. Use polling
    use_interrupt: false
    #interrupt_type: FALLING
    filters: 
      - delayed_on: 10ms   
    on_press:
      then:

      - stepper.report_position:
          id: driver
          position: ${max_distance_steps}
      - stepper.set_target:
          id: driver
          target: ${max_distance_steps}

      - cover.stop: glasscalibur_cover

      - logger.log: "LIMIT 1 PRESSED"

      # - cover.template.publish:
      #     id: glasscalibur_cover
      #     position: 1.0
          

  - platform: gpio
    name: Close Limit Switch
    id: limit_switch_2
    pin:
      number: GPIO3
      mode: INPUT
      inverted: true
    # Interrupts are not reliable, they constatnly miss. Use polling
    use_interrupt: false
    #interrupt_type: FALLING
    # Optional: filters to prevent noise from triggering the sensor
    filters: 
      - delayed_on: 10ms   
    on_press:
      then:

      - stepper.report_position:
          id: driver
          position: 0
      - stepper.set_target:
          id: driver
          target: 0

      - cover.stop: glasscalibur_cover

      - logger.log: "LIMIT 2 PRESSED"
      # - cover.template.publish:
      #     id: glasscalibur_cover
      #     position: 0

cover:
  - platform: template
    id: glasscalibur_cover
    name: Glasscalibur
    has_position: true
    lambda: "return (float(id(driver)->current_position) / float(${max_distance_steps}));"

    stop_action:
      - logger.log: "COVER stop_action"
      - stepper.stop: driver

    open_action:
      - logger.log: "COVER open_action"
      - stepper.set_target:
          id: driver
          target: ${max_distance_steps}
      # Works to set current_operation but causes no movement and crash
      # - cover.template.publish:
      #     id: glasscalibur_cover
      #     current_operation : OPENING
      
    close_action:
      - logger.log: "COVER close_action"
      - stepper.set_target:
          id: driver
          target: 0

    position_action:
      - logger.log: "COVER position_action"
      - stepper.set_target:
          id: driver
          target: !lambda return pos * ${max_distance_steps};

    #These don't actually work. But they should   
    # on_opening:
    #   - logger.log: "COVER Opening"
    #   - cover.template.publish:
    #       id: glasscalibur_cover
    #       current_operation : OPENING
    # on_opened:
    #   - logger.log: "COVER Open"
    #   - cover.template.publish:
    #       id: glasscalibur_cover
    #       current_operation : IDLE
    # on_closing:
    #   - logger.log: "COVER Closing"
    #   - cover.template.publish:
    #       id: glasscalibur_cover
    #       current_operation : CLOSING
    # on_closed:
    #   - logger.log: "COVER Closed"
    #   - cover.template.publish:
    #       id: glasscalibur_cover
    #       current_operation : IDLE
