external_components:
  - source: github://slimcdk/esphome-custom-components
    components: [tmc2209_hub, tmc2209, stepper]

globals:
  - id: global_irun
    type: int
    restore_value: yes
    initial_value: '25'
  - id: global_max_speed
    type: int
    restore_value: yes
    initial_value: '1500'
  - id: global_acceleration
    type: int
    restore_value: yes
    initial_value: '1500'
  - id: global_sgthrs
    type: int
    restore_value: yes
    initial_value: '100'
  - id: global_tcoolthrs
    type: int
    restore_value: yes
    initial_value: '100'

substitutions:
  steps_per_revolution: "1600"
  max_distance_revs: "231.9207"
  max_distance_steps: "341387"

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome

logger:
  level: DEBUG

esp32:
  variant: esp32c6
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esphome:
  name: "glasscalibur-usb-1"
  friendly_name: "Glasscalibur USB 1"
  on_boot:
    # - priority: -100
    #   then:
      - logger.log: "CHECKING LIMIT SWITCHES"
      - if:      # NEED TO CHECK IF EITHER LIMIT SWITCH IS PRESSED AND SET POSITION BASED ON THAT
          condition:
            binary_sensor.is_on: limit_switch_1  # Check if switch is pressed
          then:
            - logger.log: "SETTING LIMIT 1"
            - stepper.report_position:
                id: driver
                position: ${max_distance_steps}
            - stepper.set_target:
                id: driver
                target: ${max_distance_steps}
      - if:
          condition:
            binary_sensor.is_on: limit_switch_2  # Check if switch is pressed
          then:
            - logger.log: "SETTING LIMIT 2"
            - stepper.report_position:
                id: driver
                position: 0
            - stepper.set_target:
                id: driver
                target: 0

      - stepper.set_speed:
          id: driver
          speed: !lambda "return id(global_max_speed);"
      - stepper.set_acceleration:
          id: driver
          acceleration: !lambda "return id(global_acceleration);"

      - tmc2209.configure:
          direction: ccw
          microsteps: 8
          interpolation: true
          tcool_threshold: !lambda "return id(global_tcoolthrs);"
      - tmc2209.stallguard:
          threshold: !lambda "return id(global_sgthrs);"
      - tmc2209.currents:
          standstill_mode: freewheeling
          irun: !lambda "return id(global_irun);" #global variable
          ihold: 0
          tpowerdown: 0
          iholddelay: 0

output:
  - platform: ledc
    pin: GPIO5
    id: buzzer

uart:
  tx_pin: 1
  rx_pin: 0
  baud_rate: 500000

stepper:
  - platform: tmc2209
    id: driver
    max_speed: 1200 steps/s # Faster speed is louder #2000 good. #1500 great
    acceleration: 100 steps/s^2
    deceleration: inf # Stop immediately
    config_dump_include_registers: true
    rsense: 220 mOhm
    vsense: False
    enn_pin: 8
    index_pin: 6
    diag_pin: 14
    on_stall:
      - stepper.stop: driver
      - logger.log: "MOTOR STALLED!!!"

binary_sensor:
  - platform: gpio
    name: Button 1
    id: btn1
    pin:
      number: GPIO23
      mode: INPUT
      inverted: true
    filters:
      - delayed_on: 10ms
    on_multi_click:

      # --- Single Click ---
      - timing:
          - ON for at most 1.0s
          - OFF for at least 0.5s
        then:
          - cover.close: glasscalibur_cover
          # - if:
          #     condition: ## If moving, then stop
          #       lambda: return (id(glasscalibur_cover).current_operation != COVER_OPERATION_IDLE); # Should evaluate to TRUE if moving
          #     then:
          #       - cover.stop: glasscalibur_cover
          #     else: ## If not moving, then close
          #       - cover.close: glasscalibur_cover

          # - output.turn_on: buzzer
          # - output.ledc.set_frequency:
          #     id: buzzer
          #     frequency: "2700Hz"
          # - output.set_level:
          #     id: buzzer
          #     level: "50%"
          # - delay: 1s
          # - output.turn_off: buzzer

      # --- Double Click ---          
      - timing:
          - ON for at most 1.0s
          - OFF for at most 0.3s
          - ON for at most 1.0s
          - OFF for at least 0.5s
        then:
          - cover.open: glasscalibur_cover

          # - output.turn_on: buzzer
          # - output.ledc.set_frequency:
          #     id: buzzer
          #     frequency: "2700Hz"
          # - output.set_level:
          #     id: buzzer
          #     level: "50%"
          # - delay: 1s
          # - output.turn_off: buzzer

  - platform: gpio
    name: Open Limit Switch
    id: limit_switch_1
    pin:
      number: GPIO15
      mode: INPUT
      inverted: true
    # Interrupts are not reliable, they constatnly miss. Use polling
    use_interrupt: false
    #interrupt_type: FALLING
    filters: 
      - delayed_on: 10ms   
    on_press:
      then:

      - stepper.report_position:
          id: driver
          position: ${max_distance_steps}
      - stepper.set_target:
          id: driver
          target: ${max_distance_steps}

      - cover.stop: glasscalibur_cover

      - logger.log: "LIMIT 1 PRESSED"

      # - cover.template.publish:
      #     id: glasscalibur_cover
      #     position: 1.0
          

  - platform: gpio
    name: Close Limit Switch
    id: limit_switch_2
    pin:
      number: GPIO3
      mode: INPUT
      inverted: true
    # Interrupts are not reliable, they constatnly miss. Use polling
    use_interrupt: false
    #interrupt_type: FALLING
    # Optional: filters to prevent noise from triggering the sensor
    filters: 
      - delayed_on: 10ms   
    on_press:
      then:

      - stepper.report_position:
          id: driver
          position: 0
      - stepper.set_target:
          id: driver
          target: 0

      - cover.stop: glasscalibur_cover

      - logger.log: "LIMIT 2 PRESSED"
      # - cover.template.publish:
      #     id: glasscalibur_cover
      #     position: 0

cover:
  - platform: template
    id: glasscalibur_cover
    name: Glasscalibur
    has_position: true
    lambda: "return (float(id(driver)->current_position) / float(${max_distance_steps}));"

    stop_action:
      - logger.log: "COVER stop_action"
      - stepper.stop: driver

    open_action:
      - logger.log: "COVER open_action"
      - stepper.set_target:
          id: driver
          target: ${max_distance_steps}
      - cover.template.publish:
          id: glasscalibur_cover
          current_operation: OPENING

    close_action:
      - logger.log: "COVER close_action"
      - stepper.set_target:
          id: driver
          target: 0
      - cover.template.publish:
          id: glasscalibur_cover
          current_operation: CLOSING

    position_action:
      - logger.log: "COVER position_action"
      - stepper.set_target:
          id: driver
          target: !lambda return pos * ${max_distance_steps};

    #These don't actually work. But they should   
    on_opening:
      - logger.log: "COVER Opening"
      - cover.template.publish:
          id: glasscalibur_cover
          current_operation : OPENING
    on_opened:
      - logger.log: "COVER Open"
      - cover.template.publish:
          id: glasscalibur_cover
          current_operation : IDLE
    on_closing:
      - logger.log: "COVER Closing"
      - cover.template.publish:
          id: glasscalibur_cover
          current_operation : CLOSING
    on_closed:
      - logger.log: "COVER Closed"
      - cover.template.publish:
          id: glasscalibur_cover
          current_operation : IDLE

number:
# SET acceleration
  - platform: template
    name: acceleration
    step: 100
    min_value: 100
    max_value: 10000
    mode: SLIDER
    entity_category: CONFIG
    lambda: return id(global_acceleration);
    update_interval: 1s
    set_action: 
      then:
        - globals.set:
            id: global_acceleration
            value: !lambda "return x;"
        - stepper.set_acceleration:
            id: driver
            acceleration: !lambda "return id(global_acceleration);"

# SET max_speed
  - platform: template
    name: max_speed
    step: 100
    min_value: 100
    max_value: 10000
    mode: SLIDER
    entity_category: CONFIG
    lambda: return id(global_max_speed);
    update_interval: 1s
    set_action: 
      then:
        - globals.set:
            id: global_max_speed
            value: !lambda "return x;"
        - stepper.set_speed:
            id: driver
            speed: !lambda "return id(global_max_speed);"

# SET irun
  - platform: template
    name: irun
    step: 1
    min_value: 1
    max_value: 31
    mode: BOX
    entity_category: CONFIG
    lambda: return id(driver)->read_field(IRUN_FIELD);
    update_interval: 1s
    set_action: 
      then:
        - globals.set:
            id: global_irun
            value: !lambda "return x;"
        - tmc2209.currents:
            irun: !lambda "return id(global_irun);"

# SET TCOOL
  - platform: template
    name: TCOOLTHRS
    step: 1
    min_value: 0
    max_value: 1048575
    mode: BOX
    entity_category: CONFIG
    lambda: return id(driver)->read_register(TCOOLTHRS);
    update_interval: 1s
    set_action: 
      then:
        - globals.set:
            id: global_tcoolthrs
            value: !lambda "return x;"
        - lambda: id(driver)->write_register(TCOOLTHRS, x);


# SET SGTHRS
  - platform: template
    name: SGTHRS
    step: 1
    min_value: 0
    max_value: 255
    mode: SLIDER
    entity_category: CONFIG
    lambda: return id(driver)->read_register(SGTHRS);
    update_interval: 1s
    set_action: 
      then:
        - globals.set:
            id: global_sgthrs
            value: !lambda "return x;"
        - lambda: id(driver)->write_register(SGTHRS, x);

i2c:
  sda: GPIO19
  scl: GPIO20
  scan: true
  id: i2c_bus

# Display using sensor
sensor:
  - platform: template
    name: "TSTEP Sensor" # SHOW TSTEP
    lambda: return id(driver)->read_register(TSTEP);
    update_interval: 5s
    entity_category: DIAGNOSTIC
  - platform: template # SHOW SG_RESULT
    name: "SG_RESULT Sensor"
    lambda: return id(driver)->read_register(SG_RESULT);
    update_interval: 1s
    entity_category: DIAGNOSTIC

  - platform: tmp1075
    name: "Motor Temperature"
    update_interval: 3s
    entity_category: DIAGNOSTIC
    i2c_id: i2c_bus
    address: 0x49
    accuracy_decimals: 2
    # --- ACTION ON TEMPERATURE EXAMPLE ---
    on_value_range:
      - above: 80
        then:
          - cover.stop: glasscalibur_cover
          - logger.log: "TOO HOT!"
    
    # USE ALERT PIN IN FUTURE instead of polling